# This file contains the [pre-commit](https://pre-commit.com/) configuration of this repository.
# More on which specific pre-commit hooks we use can be found in README.md.
---
minimum_pre_commit_version: "2.9.2"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: local
    hooks:
      - id: isort
        name: iSort - Sorts imports.
        description: Sorts your import for you.
        entry: isort
        language: python
        types:
          - python
        require_serial: true
        exclude: examples/*
        additional_dependencies:
          - isort==5.10.1
      - id: black
        name: Black - Auto-formatter.
        description: Black is the uncompromising Python code formatter. Writing to files.
        entry: black
        language: python
        types:
          - python
        require_serial: true
        additional_dependencies:
          - black==22.6.0
      - id: flake8
        name: Flake8 - Enforce code style and doc.
        description: A command-line utility for enforcing style consistency across Python projects.
        entry: flake8
        args:
         - --config=.flake8
        language: python
        types:
          - python
        require_serial: true
        additional_dependencies:
          - flake8==4.0.1
      - id: mypy
        name: mypy - Static type checking
        description: Mypy helps ensure that we use our functions and variables correctly by checking the types.
        entry: mypy
        args:
          - --ignore-missing-imports
          - --scripts-are-modules
        language: python
        types:
          - python
        require_serial: true
        additional_dependencies:
          - mypy==0.961
